-- ════════════════════════════════════════════════════════════════════
--  zero-cost-ops — Supabase PostgreSQL Schema
--  Version: 1.0.0
--  Compatible with: PostgreSQL 15+ (Supabase managed)
--
--  Tables:
--    1. metadata    — Core content entries (symbols, events, notes, etc.)
--    2. users       — User authentication and profile data
--    3. diagnostics — Diagnostic session results
--    4. bookings    — Appointment/scheduling records
--    5. payments    — Payment transaction records
--
--  Usage:
--    Paste this into Supabase Dashboard > SQL Editor > New Query > Run
--    Or: supabase db push (with Supabase CLI)
--
--  Notes:
--    - RLS (Row-Level Security) is enabled on all tables
--    - All tables have automated updated_at timestamps
--    - GIN indexes on array/JSONB columns for efficient filtering
-- ════════════════════════════════════════════════════════════════════


-- ── SHARED FUNCTION: update_updated_at ───────────────────────────────
-- Automatically updates the updated_at column on any row modification.
-- Applied to all tables via triggers below.

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ════════════════════════════════════════════════════════════════════
--  TABLE 1: METADATA
--  Core content store. Each row is one unit of content (a message,
--  document, event, note) that has been ingested and classified.
--
--  Populated by: WF-01 ingestion pipeline via n8n
--  Updated by:   WF-04 timeline engine
--  Read by:      Dashboard via Supabase anon key REST API
-- ════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS metadata (
    -- Primary key — UUID generated by PostgreSQL
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Unique identifier for this entry (format: auto_{source}_{timestamp})
    -- Example: auto_slack_1743400000000, auto_github_1743300000000
    file_name       TEXT UNIQUE NOT NULL,

    -- Content type — free text (document, message, event, note, etc.)
    type            TEXT,

    -- 1-2 sentence AI-generated summary of the content
    summary         TEXT,

    -- 3-5 keyword tags for filtering/search
    -- Example: '{infrastructure, supabase, deployment}'
    tags            TEXT[] DEFAULT '{}',

    -- Named entities extracted from content (people, companies, concepts)
    -- Example: '{Claude AI, Supabase, Render}'
    entities        TEXT[] DEFAULT '{}',

    -- Emotional tone of the content (positive, neutral, tension, resolved, etc.)
    emotional_tone  TEXT,

    -- Source system that generated this entry
    -- Example: slack, github, cloudflare, manual, twitter
    source          TEXT NOT NULL,

    -- High-level thematic categories
    themes          TEXT[] DEFAULT '{}',

    -- Abstract concepts mentioned
    concepts        TEXT[] DEFAULT '{}',

    -- Search keywords (broader than tags)
    keywords        TEXT[] DEFAULT '{}',

    -- MIME type of original content (text/plain, application/json, etc.)
    mime_type       TEXT,

    -- Semantic cluster assignment (set by cross-linking workflow)
    cluster         TEXT,

    -- UUIDs of related entries (cross-linked by WF-02)
    related_ids     UUID[] DEFAULT '{}',

    -- Date the content was created/refers to (estimated by AI)
    -- Format: YYYY-MM-DD or YYYY
    date_estimated  TEXT,

    -- Time period cluster — used by WF-04 for narrative arc
    -- Values: '1974-1990' | '2019-2023' | '2024-2026'
    -- CUSTOMIZE: Change these periods to match your project's timeline
    timeline_group  TEXT,

    -- Narrative role in the overall story arc
    -- Values: symbol|system|pilot|origin|exploration|setup|conflict|realisation|integration
    -- CUSTOMIZE: Define your own narrative taxonomy here
    narrative_role  TEXT,

    -- Timestamps
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_metadata_file_name       ON metadata(file_name);
CREATE INDEX IF NOT EXISTS idx_metadata_source          ON metadata(source);
CREATE INDEX IF NOT EXISTS idx_metadata_narrative_role  ON metadata(narrative_role);
CREATE INDEX IF NOT EXISTS idx_metadata_timeline_group  ON metadata(timeline_group);
CREATE INDEX IF NOT EXISTS idx_metadata_tags            ON metadata USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_metadata_entities        ON metadata USING GIN(entities);
CREATE INDEX IF NOT EXISTS idx_metadata_related_ids     ON metadata USING GIN(related_ids);

-- RLS
ALTER TABLE metadata ENABLE ROW LEVEL SECURITY;

-- Anyone (including anonymous dashboard) can read metadata
CREATE POLICY "Public read access"
ON metadata FOR SELECT
USING (true);

-- Only authenticated users (n8n service role) can insert
CREATE POLICY "Authenticated insert"
ON metadata FOR INSERT
TO authenticated
WITH CHECK (true);

-- Only authenticated users can update
CREATE POLICY "Authenticated update"
ON metadata FOR UPDATE
TO authenticated
USING (true);

-- Trigger: auto-update updated_at on modification
CREATE TRIGGER metadata_updated_at
BEFORE UPDATE ON metadata
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


-- ════════════════════════════════════════════════════════════════════
--  TABLE 2: USERS
--  Authentication and user profile management.
--  Mirrors Supabase Auth's auth.users table with additional profile data.
--
--  Populated by: Supabase Auth (automatic on signup)
--  Supports: GitHub OAuth, Google OAuth, Email Magic Link
-- ════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS users (
    -- References auth.users — cascades on delete
    id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,

    -- User's email address (from OAuth provider or email signup)
    email           TEXT UNIQUE NOT NULL,

    -- Display name (from OAuth profile or user-set)
    full_name       TEXT,

    -- Profile picture URL (from OAuth provider)
    avatar_url      TEXT,

    -- OAuth provider used (github, google, email)
    oauth_provider  TEXT,

    -- OAuth provider's user ID (for de-duplication)
    oauth_id        TEXT,

    -- Timestamps
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    last_sign_in_at TIMESTAMPTZ
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_email          ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_oauth_provider ON users(oauth_provider);

-- RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Users can only read their own profile
CREATE POLICY "Users read own data"
ON users FOR SELECT
TO authenticated
USING (auth.uid() = id);

-- Users can only update their own profile
CREATE POLICY "Users update own data"
ON users FOR UPDATE
TO authenticated
USING (auth.uid() = id);

-- Trigger
CREATE TRIGGER users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


-- ════════════════════════════════════════════════════════════════════
--  TABLE 3: DIAGNOSTICS
--  Stores diagnostic session results.
--  Adapt this table for your own multi-step form/questionnaire flows.
--
--  The 4-step structure (step_1 through step_4) maps to whatever
--  question flow your application uses.
-- ════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS diagnostics (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Optional user association (can be anonymous)
    user_id             UUID REFERENCES users(id) ON DELETE SET NULL,

    -- Unique session identifier (generated by frontend)
    session_id          TEXT UNIQUE NOT NULL,

    -- Step responses — adapt to your question flow
    step_1_response     TEXT,
    step_2_response     TEXT,
    step_3_response     TEXT,
    step_4_response     TEXT,

    -- Structured analysis results (JSON from your AI processing)
    -- Example: { "score": 0.78, "patterns": ["pattern1"], "recommendations": [...] }
    analysis            JSONB,

    -- Array of recommended next actions
    recommended_actions TEXT[],

    -- Session status: in_progress | complete | abandoned
    status              TEXT DEFAULT 'in_progress',

    -- Timestamps
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    completed_at        TIMESTAMPTZ
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_diagnostics_user_id    ON diagnostics(user_id);
CREATE INDEX IF NOT EXISTS idx_diagnostics_session_id ON diagnostics(session_id);
CREATE INDEX IF NOT EXISTS idx_diagnostics_status     ON diagnostics(status);
CREATE INDEX IF NOT EXISTS idx_diagnostics_analysis   ON diagnostics USING GIN(analysis);

-- RLS
ALTER TABLE diagnostics ENABLE ROW LEVEL SECURITY;

-- Users can only read their own sessions
CREATE POLICY "Users read own diagnostics"
ON diagnostics FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Anonymous sessions allowed (for public diagnostic flows)
CREATE POLICY "Public insert diagnostics"
ON diagnostics FOR INSERT
WITH CHECK (true);


-- ════════════════════════════════════════════════════════════════════
--  TABLE 4: BOOKINGS
--  Appointment/scheduling records.
--  Built for Calendly integration but adaptable to any scheduler.
--
--  Populated by: Calendly webhooks via n8n
-- ════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS bookings (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID REFERENCES users(id) ON DELETE SET NULL,
    diagnostic_id           UUID REFERENCES diagnostics(id) ON DELETE SET NULL,

    -- Calendly-specific fields (replace with your scheduler's IDs)
    calendly_event_uri      TEXT UNIQUE,
    calendly_invitee_uri    TEXT,
    event_type              TEXT,

    -- Scheduling details
    scheduled_at            TIMESTAMPTZ NOT NULL,
    duration_minutes        INTEGER DEFAULT 60,

    -- Status: scheduled | cancelled | completed | no_show
    status                  TEXT DEFAULT 'scheduled',
    cancellation_reason     TEXT,

    -- Timestamps
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_bookings_user_id               ON bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_diagnostic_id         ON bookings(diagnostic_id);
CREATE INDEX IF NOT EXISTS idx_bookings_calendly_event_uri    ON bookings(calendly_event_uri);
CREATE INDEX IF NOT EXISTS idx_bookings_scheduled_at          ON bookings(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_bookings_status                ON bookings(status);

-- RLS
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Users can read their own bookings
CREATE POLICY "Users read own bookings"
ON bookings FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Service role (n8n webhooks) has full access for Calendly sync
CREATE POLICY "Service role full access"
ON bookings FOR ALL
TO service_role
USING (true);

-- Trigger
CREATE TRIGGER bookings_updated_at
BEFORE UPDATE ON bookings
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


-- ════════════════════════════════════════════════════════════════════
--  TABLE 5: PAYMENTS
--  Payment transaction records.
--  Built for Stripe integration but adaptable to any payment processor.
--
--  Populated by: Stripe webhooks via n8n
--  Note: Never store card numbers, CVV, or full PANs here.
-- ════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS payments (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                     UUID REFERENCES users(id) ON DELETE SET NULL,
    booking_id                  UUID REFERENCES bookings(id) ON DELETE SET NULL,

    -- Stripe-specific fields (replace with your processor's IDs)
    stripe_payment_intent_id    TEXT UNIQUE NOT NULL,
    stripe_customer_id          TEXT,

    -- Amount in smallest currency unit (cents for EUR/USD)
    -- Example: 19800 = €198.00
    amount_cents                INTEGER NOT NULL,
    currency                    TEXT DEFAULT 'EUR',

    -- Status: pending | succeeded | failed | refunded | disputed
    status                      TEXT DEFAULT 'pending',

    -- Additional structured data from payment processor
    -- Example: { "receipt_url": "...", "payment_method": "card" }
    metadata                    JSONB,

    -- Timestamps
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payments_user_id                     ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_booking_id                  ON payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_stripe_payment_intent_id    ON payments(stripe_payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_payments_status                      ON payments(status);

-- RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Users can read their own payment records
CREATE POLICY "Users read own payments"
ON payments FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Service role (n8n webhooks) has full access for Stripe sync
CREATE POLICY "Service role full access"
ON payments FOR ALL
TO service_role
USING (true);

-- Trigger
CREATE TRIGGER payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


-- ════════════════════════════════════════════════════════════════════
--  RELATIONSHIPS SUMMARY
--
--  users (1) ──< (many) diagnostics
--  users (1) ──< (many) bookings
--  users (1) ──< (many) payments
--
--  diagnostics (1) ──< (many) bookings
--  bookings (1) ──< (many) payments
--
--  metadata.related_ids[] ──> metadata.id  (self-referential)
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  SECURITY CHECKLIST
--  Before going live, verify:
--
--  [x] RLS enabled on all tables
--  [x] Foreign key constraints enforced
--  [ ] Service role key stored in Render env vars (NOT in code)
--  [ ] Anon key safe to expose (read-only access on metadata only)
--  [x] Sensitive data NOT stored (no API keys, no card numbers)
--  [x] Timestamps on all tables
--  [x] Indexes on foreign keys
--  [x] GIN indexes on array/JSONB columns
--  [ ] Webhook signature verification enabled in n8n
-- ════════════════════════════════════════════════════════════════════
